### ISSUE TITLE
[ReferenceError: Property 't' doesn't exist]

### ISSUE THREAD

**Issue by deflexable** [luncheon/simplify-svg-path#1]
this error seems to be coming from index.min.js

**Comment by luncheon** [comment]
Could you reproduce it in CodePen or CodeSandbox (or similar)?

**Comment by Eduardoleor** [comment]
This error is reproduced in: https://github.com/BenJeau/react-native-draw/issues/63

<img width="388" alt="Screenshot 2022-11-22 at 15 46 39" src="https://user-images.githubusercontent.com/18225159/203427709-76394d5b-a75f-460e-8b39-d4e71486dd1b.png">

**Comment by luncheon** [comment]
OK. I haven't tried it, but I guess it doesn't work in react native.

v0.2.0, which does not minified, is now available.

The reason for minifying was for mangling class fields. Now I have stopped using classes and the object field names are now single characters.

**Comment by hongdthaui** [comment]
update version 0.2.0 for @luncheon/simplify-svg-path on @benjeau/react-native-draw/node_moduls
i tried and ok

**Comment by ph3rro** [comment]
same as hongdthaui, that works

**Comment by luncheon** [comment]
@hongdthaui @sickopickle
thanks for confirming that it works.

**Comment by drvn-eb** [comment]
@luncheon just found out this error upgrading from 0.1.4 to 0.1.5 , nice to see that it's fixed in 0.2.0, thanks for that!

It would be nice to have either a changelog or to remove / mark as problematic the 0.1.5 release on npm
